type: "ucblosbo"
beta: 
  type: "constant" # alternative "constant", "add-gp-ucb", "srinivas", "fiedler"
  value: 2
initial_safe_points: 1
E: 0.01
max_iterations: 20
acqf: "maxvar" # alternative "maxvar", "ucb"