domain_bounds:
- 0
- 1
domain_size: 1
function_number: 60
gamma: 0.2
kernel: SE
lipschitz_constant: 22.9171375765995
mean: 2.2607905665106856
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 4.501766036960475
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 60
reachable_safe_set:
- 0.554
- 1.0
rkhs_norm: 10
safety_threshold: 2.038234355750742
sampling: onb
std: 1.1127810537997196
type: pre_rkhs_se
