domain_bounds:
- 0
- 1
domain_size: 1
function_number: 2
gamma: 0.2
kernel: SE
lipschitz_constant: 32.87828191414907
mean: 0.9166948706883808
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 7.084476125999032
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 2
reachable_safe_set:
- 0.0
- 0.266
rkhs_norm: 10
safety_threshold: 0.5485455793866949
sampling: onb
std: 1.84074645650843
type: pre_rkhs_se
