domain_bounds:
- 0
- 1
domain_size: 1
function_number: 21
gamma: 0.2
kernel: SE
lipschitz_constant: 28.39509064090695
mean: 2.172002864976265
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 5.210153317194266
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 21
reachable_safe_set:
- 0.577
- 1.0
rkhs_norm: 10
safety_threshold: 1.781860862905452
sampling: onb
std: 1.9507100103540647
type: pre_rkhs_se
