domain_bounds:
- 0
- 1
domain_size: 1
function_number: 79
gamma: 0.2
kernel: SE
lipschitz_constant: 33.44348070814182
mean: -1.058832189837955
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 7.45194264608246
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 79
reachable_safe_set:
- 0.0
- 0.38
rkhs_norm: 10
safety_threshold: -1.90673503847635
sampling: onb
std: 4.239514243191976
type: pre_rkhs_se
