domain_bounds:
- 0
- 1
domain_size: 1
function_number: 96
gamma: 0.2
kernel: SE
lipschitz_constant: 29.1208245026926
mean: -2.834892174444682
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: -7.663378517580272e-05
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 96
reachable_safe_set:
- 0.357
- 1.0
rkhs_norm: 10
safety_threshold: -3.4492566654312906
sampling: onb
std: 3.071822454933044
type: pre_rkhs_se
