domain_bounds:
- 0
- 1
domain_size: 1
function_number: 7
gamma: 0.2
kernel: SE
lipschitz_constant: 39.73062891166542
mean: -3.469653689658998
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 1.3132941349918663
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 7
reachable_safe_set:
- 0.762
- 1.0
rkhs_norm: 10
safety_threshold: -4.074224031310504
sampling: onb
std: 3.02285170825753
type: pre_rkhs_se
