domain_bounds:
- 0
- 1
domain_size: 1
function_number: 0
gamma: 0.2
kernel: SE
lipschitz_constant: 39.10253405313565
mean: 2.9585708333557506
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 9.26445394212315
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 0
reachable_safe_set:
- 0.722
- 1.0
rkhs_norm: 10
safety_threshold: 2.420207695940472
sampling: onb
std: 2.6918156870763927
type: pre_rkhs_se
