domain_bounds:
- 0
- 1
domain_size: 1
function_number: 77
gamma: 0.2
kernel: SE
lipschitz_constant: 43.449555646141356
mean: -1.5984662481194412
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 2.68384768448466
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 77
reachable_safe_set:
- 0.532
- 1.0
rkhs_norm: 10
safety_threshold: -2.2347563499531518
sampling: onb
std: 3.181450509168553
type: pre_rkhs_se
