domain_bounds:
- 0
- 1
domain_size: 1
function_number: 98
gamma: 0.2
kernel: SE
lipschitz_constant: 16.18872660121394
mean: -1.8068235643801784
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: -0.4306849903217045
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 98
reachable_safe_set:
- 0.635
- 1.0
rkhs_norm: 10
safety_threshold: -2.02587453693686
sampling: onb
std: 1.0952548627834078
type: pre_rkhs_se
