domain_bounds:
- 0
- 1
domain_size: 1
function_number: 34
gamma: 0.2
kernel: SE
lipschitz_constant: 28.75569677492915
mean: -2.475223946824437
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 2.9267783824312454
path: config/rkhs_function_configs/pre_rkhs_se/
random_seed: 34
reachable_safe_set:
- 0.617
- 1.0
rkhs_norm: 10
safety_threshold: -3.145501065084572
sampling: onb
std: 3.3513855913006747
type: pre_rkhs_se
