type: "matern32" 
learn_hyperparameters: false
ard: false
lengthscale: 
  prior_mean: 0.2
  prior_std: 1
outputscale: 
  prior_mean: 1
  prior_std: 1
prior_mean: 0
noise: 
  prior_mean: 0.01
  prior_std: 1