type: "gaussian_10D"
lipschitz_constant: 8
noise_lvl: 0.01
domain_size: 10
domain_bounds: 
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
  - [-1, 1]
safety_threshold: 0.2 # safety threshold
optimum: 1