domain_bounds:
- 0
- 1
domain_size: 1
function_number: 91
gamma: 0.2
kernel: Matern
lipschitz_constant: 16.65213386560603
mean: -0.8694227491647476
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 1.8344558300449745
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 91
reachable_safe_set:
- 0.36
- 1.0
rkhs_norm: 10
safety_threshold: -1.1085428353372702
sampling: onb
std: 1.195600430862613
type: pre_rkhs_matern32
