domain_bounds:
- 0
- 1
domain_size: 1
function_number: 32
gamma: 0.2
kernel: Matern
lipschitz_constant: 28.158250799254578
mean: 2.678949770405733
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 5.653963260907002
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 32
reachable_safe_set:
- 0.84
- 1.0
rkhs_norm: 10
safety_threshold: 2.3652421541577446
sampling: onb
std: 1.56853808123994
type: pre_rkhs_matern32
