domain_bounds:
- 0
- 1
domain_size: 1
function_number: 79
gamma: 0.2
kernel: Matern
lipschitz_constant: 34.12085330102241
mean: -0.971872134090781
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 7.339340400647652
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 79
reachable_safe_set:
- 0.0
- 0.397
rkhs_norm: 10
safety_threshold: -1.7458279258226808
sampling: onb
std: 3.8697789586594986
type: pre_rkhs_matern32
