domain_bounds:
- 0
- 1
domain_size: 1
function_number: 0
gamma: 0.2
kernel: Matern
lipschitz_constant: 41.096678340622326
mean: 2.7410125179676146
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 9.240073817177073
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 0
reachable_safe_set:
- 0.725
- 1.0
rkhs_norm: 10
safety_threshold: 2.237241631498235
sampling: onb
std: 2.5188544323468967
type: pre_rkhs_matern32
