domain_bounds:
- 0
- 1
domain_size: 1
function_number: 10
gamma: 0.2
kernel: Matern
lipschitz_constant: 43.99429874381152
mean: 1.651536265161334
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 6.626315245973178
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 10
reachable_safe_set:
- 0.0
- 0.16
rkhs_norm: 10
safety_threshold: 1.182608590980545
sampling: onb
std: 2.344638370903944
type: pre_rkhs_matern32
