domain_bounds:
- 0
- 1
domain_size: 1
function_number: 2
gamma: 0.2
kernel: Matern
lipschitz_constant: 34.74054685604508
mean: 0.8235968702176283
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 6.501170996189832
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 2
reachable_safe_set:
- 0.0
- 0.297
rkhs_norm: 10
safety_threshold: 0.5157068882134865
sampling: onb
std: 1.5394499100207089
type: pre_rkhs_matern32
