domain_bounds:
- 0
- 1
domain_size: 1
function_number: 46
gamma: 0.2
kernel: Matern
lipschitz_constant: 38.74900130523962
mean: -0.5497116410163759
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 5.4492037427484
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 46
reachable_safe_set:
- 0.0
- 0.301
rkhs_norm: 10
safety_threshold: -0.9546327471253679
sampling: onb
std: 2.0246055305449597
type: pre_rkhs_matern32
