domain_bounds:
- 0
- 1
domain_size: 1
function_number: 27
gamma: 0.2
kernel: Matern
lipschitz_constant: 58.428543179023634
mean: -2.353176357347489
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 3.1295819735643082
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 27
reachable_safe_set:
- 0.0
- 0.34
rkhs_norm: 10
safety_threshold: -2.9126113007076633
sampling: onb
std: 2.797174716800872
type: pre_rkhs_matern32
