domain_bounds:
- 0
- 1
domain_size: 1
function_number: 44
gamma: 0.2
kernel: Matern
lipschitz_constant: 21.06863351917008
mean: -1.34117592338972
n_basepoints: 10
n_bfuncs_min: 10
noise_lvl: 0.01
nu: 1.5
optimum: 2.3694238624573005
path: config/rkhs_function_configs/pre_rkhs_matern32/
random_seed: 44
reachable_safe_set:
- 0.0
- 0.381
rkhs_norm: 10
safety_threshold: -1.685056997442296
sampling: onb
std: 1.71940537026288
type: pre_rkhs_matern32
