domain_bounds:
- 0
- 1
domain_size: 1
function_number: 82
gamma: 0.2
kernel: SE
lipschitz_constant: 18.346723653446457
mean: -1.12961999341569
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 0.0
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 82
reachable_safe_set:
- 0.0
- 0.17
rkhs_norm: 10
safety_threshold: -1.325987691273991
sampling: onb
std: 0.9818384892915047
type: rkhs_onb_se
