domain_bounds:
- 0
- 1
domain_size: 1
function_number: 59
gamma: 0.2
kernel: SE
lipschitz_constant: 28.517354929241208
mean: -1.66120547288007
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 0.0
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 59
reachable_safe_set:
- 0.0
- 0.068
rkhs_norm: 10
safety_threshold: -1.8717051739903405
sampling: onb
std: 1.0524985055513525
type: rkhs_onb_se
