domain_bounds:
- 0
- 1
domain_size: 1
function_number: 20
gamma: 0.2
kernel: SE
lipschitz_constant: 15.886246912094379
mean: -1.0389935246604443
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 0.0
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 20
reachable_safe_set:
- 0.0
- 0.278
rkhs_norm: 10
safety_threshold: -1.2586595168593193
sampling: onb
std: 1.0983299609943749
type: rkhs_onb_se
