domain_bounds:
- 0
- 1
domain_size: 1
function_number: 5
gamma: 0.2
kernel: SE
lipschitz_constant: 9.280249811628218
mean: 1.1567029573044527
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 2.089919267581163
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 5
reachable_safe_set:
- 0.0
- 0.24
rkhs_norm: 10
safety_threshold: 1.0248104027288594
sampling: onb
std: 0.6594627728779665
type: rkhs_onb_se
