domain_bounds:
- 0
- 1
domain_size: 1
function_number: 43
gamma: 0.2
kernel: SE
lipschitz_constant: 13.613929082465491
mean: -0.6021350875521626
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 0.0
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 43
reachable_safe_set:
- 0.0
- 0.435
rkhs_norm: 10
safety_threshold: -0.7348343790620586
sampling: onb
std: 0.6634964575494803
type: rkhs_onb_se
