domain_bounds:
- 0
- 1
domain_size: 1
function_number: 15
gamma: 0.2
kernel: SE
lipschitz_constant: 15.183555340416142
mean: -0.7919379998212537
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 0.0
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 15
reachable_safe_set:
- 0.0
- 0.135
rkhs_norm: 10
safety_threshold: -0.9098256524628685
sampling: onb
std: 0.589438263208074
type: rkhs_onb_se
