domain_bounds:
- 0
- 1
domain_size: 1
function_number: 3
gamma: 0.2
kernel: SE
lipschitz_constant: 31.784128693650917
mean: -1.1289307204734234
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 0.0
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 3
reachable_safe_set:
- 0.0
- 0.048
rkhs_norm: 10
safety_threshold: -1.3229197211803716
sampling: onb
std: 0.9699450035347418
type: rkhs_onb_se
