domain_bounds:
- 0
- 1
domain_size: 1
function_number: 1
gamma: 0.2
kernel: SE
lipschitz_constant: 18.23359383081378
mean: 1.883595317749211
n_base_points: 10
n_bfuncs_min: 10
noise_lvl: 0.01
optimum: 4.310688706151141
path: config/rkhs_function_configs/onb_rkhs_se/
random_seed: 1
reachable_safe_set:
- 0.0
- 0.5
rkhs_norm: 10
safety_threshold: 1.5332080063486235
sampling: onb
std: 1.751936557002938
type: rkhs_onb_se
